name: Run MySQL and Python containers on Kubernetes

on: push

jobs:
  run-on-kubernetes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        cache: false

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Build Python Docker image
      run: docker build -t python-mysql-app:latest .

    - name: Load Python image into Minikube
      run: minikube image load python-mysql-app:latest

    - name: Apply MySQL Kubernetes manifest
      run: kubectl apply -f mysql-deployement.yaml

    - name: Wait for MySQL pod to be ready
      run: kubectl wait --for=condition=ready pod -l app=mysql --timeout=120s
    
      
    - name: Deploy Python app
      run: kubectl apply -f python-app-deployment.yaml  

    - name: Wait for Python app deployment to be ready
      run: kubectl rollout status deployment/python-app


    - name: Show logs from Python job
      run: kubectl logs deploy/python-app
